# Generated by Django 3.2.8 on 2022-02-11 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_alter_flower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='interaction.user'),
            preserve_default=False,
        ),
    ]
