# Generated by Django 4.0.3 on 2022-05-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_flower_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'permissions': [('test_flower', 'Test Flower')]},
        ),
    ]
